InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "colu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-FilterVariable(mSet, "rsd", "T", 30)
mSet<-Normalization(mSet, "NULL", "LogNorm", "AutoNorm", "AF_6", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
colVec<-c("#0015ff","#ff0000","#15ff00")
shapeVec<-c(16,17,8)
mSet<-UpdateGraphSettings(mSet, colVec, shapeVec)
grp.nm.vec<-c("QC")
mSet<-UpdateGroupItems(mSet, grp.nm.vec)
mSet<-Normalization(mSet, "NULL", "LogNorm", "AutoNorm", "AF_6", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-FC.Anal.unpaired(mSet, 2.0, 0)
mSet<-PlotFC(mSet, "fc_0_", "png", 72, width=NA)
mSet<-FC.Anal.unpaired(mSet, 2.0, 0)
mSet<-PlotFC(mSet, "fc_1_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE)
mSet<-PlotTT(mSet, "tt_0_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE)
mSet<-PlotTT(mSet, "tt_1_", "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, 0.75,F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_", "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, 0.75,F, 0.05, TRUE, "fdr")
mSet<-PlotVolcano(mSet, "volcano_1_", "png", 72, width=NA)
mSet<-PlotCorrHeatMap(mSet, "corr_0_", "png", 72, width=NA, "col", "pearson", "bwm", "overview", F, F, F, 100)
mSet<-PlotCorrHeatMap(mSet, "corr_1_", "png", 72, width=NA, "col", "pearson", "gbr", "detail", F, F, F, 999)
mSet<-PlotCorrHeatMap(mSet, "corr_1_", "tiff", 300, width=7, "col", "pearson", "gbr", "detail", F, F, F, 999)
mSet<-PlotCorrHeatMap(mSet, "corr_2_", "png", 72, width=NA, "row", "pearson", "gbr", "overview", F, F, F, 999)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,1,0)
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2,"scatter", 1);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DScore(mSet, "pca_score3d_0_", "json", 1,2,3)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,1,0)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2,"scatter", 1);
mSet<-PLSDA.CV(mSet, "L",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0)
mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", T, T, NA, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "correlation", "average","gbr", "detail", F, T, NA, T, F)
mSet<-SAM.Anal(mSet, "d.stat", FALSE, TRUE)
mSet<-PlotSAM.FDR(mSet, 1.2, "sam_view_0_", "png", 72, width=NA)
mSet<-SetSAMSigMat(mSet, 1.2)
mSet<-PlotSAM.Cmpd(mSet, "sam_imp_0_", "png", 72, width=NA)
mSet<-SAM.Anal(mSet, "d.stat", FALSE, TRUE)
mSet<-PlotSAM.FDR(mSet, 1.2, "sam_view_1_", "png", 72, width=NA)
mSet<-SetSAMSigMat(mSet, 1.2)
mSet<-PlotSAM.Cmpd(mSet, "sam_imp_1_", "png", 72, width=NA)
mSet<-Kmeans.Anal(mSet, 3)
mSet<-PlotKmeans(mSet, "km_0_", "png", 72, width=NA)
mSet<-SaveTransformedData(mSet)
